deploy_revision node['huginn']['deploy_user']['home'] do
  repository node['huginn']['repository']
  revision node['huginn']['revision']
  keep_releases node['huginn']['keep_releases']
  rollback_on_error node['huginn']['rollback_on_error']
  # enable_submodules true
  # shallow_clone true

  user node['huginn']['deploy_user']['name']
  group node['huginn']['deploy_user']['group']

  environment "RAILS_ENV" => node['huginn']['rails_env'], "RBENV_VERSION" => node['huginn']['ruby_version']

  migrate false # We handle this manually below since it doesn't work well with rbenv

  action node['huginn']['deploy_action']

  symlink_before_migrate Hash.new # Disable default

  before_migrate do
    environment_options = Hash[open("#{release_path}/.env.example").readlines.reject{|line| line =~ /^#|^\s*$/}.map {|line| line.strip.delete('"').split('=')}]
    log "%% pre-merge environment options: #{environment_options.inspect}"
    # Override any default values with those set by the user
    environment_options.merge! node['huginn']['env']

    Chef::Log.info "Rewriting Gemfile/Procfile to use unicorn"
    rbenv_execute "Rewrite Gemfile/Procfile to use unicorn" do
      cwd release_path
      user new_resource.user

      ruby_version node['huginn']['ruby_version']

      command %{
        echo >> Gemfile
        echo "gem 'unicorn'" >> Gemfile

        sed -i 's#rails server#unicorn -c config/unicorn/production.rb#' Procfile
      }
    end

    # From https://github.com/poise/application_ruby/blob/master/providers/rails.rb
    Chef::Log.info "Running bundle install"
    directory "#{new_resource.deploy_to}/shared/vendor_bundle" do
      owner new_resource.user
      group new_resource.group
      mode '0755'
    end
    directory "#{release_path}/vendor" do
      owner new_resource.user
      group new_resource.group
      mode '0755'
    end
    link "#{release_path}/vendor/bundle" do
      to "#{new_resource.deploy_to}/shared/vendor_bundle"
    end

    common_groups = %w{development test cucumber staging}
    bundle_command = "bundle install --path=vendor/bundle --without #{common_groups}"

    rbenv_execute "Bundle Install" do
      cwd release_path
      user new_resource.user
      environment environment_options

      ruby_version node['huginn']['ruby_version']

      command bundle_command
    end

    Chef::Log.info "Creating rake secret (if required)"
    rbenv_execute "create-rake-secret" do
      user new_resource.user
      cwd release_path
      environment environment_options

      ruby_version node['huginn']['ruby_version']
      creates "#{new_resource.deploy_to}/shared/rakesecret"

      command <<-EOH
      bundle exec rake secret > #{new_resource.deploy_to}/shared/rakesecret
      EOH
    end

    Chef::Log.info "Updating dotenv config file"
    file "#{new_resource.deploy_to}/shared/dotenv" do
      content <<-EOENV
# Configuration options for Huginn, generated by Chef

#{environment_options.map {|k,v| "#{k.upcase}=\"#{v}\"" }.join("\n")}
EOENV
      mode '0600'
      owner new_resource.user
      group new_resource.group
    end

    link "#{release_path}/.env" do
      to "#{new_resource.deploy_to}/shared/dotenv"
    end

    Chef::Log.info "Running rake db:create (if required)"
    rbenv_execute "rake-db-create" do
      user new_resource.user
      cwd release_path
      environment environment_options

      ruby_version node['huginn']['ruby_version']
      creates "#{new_resource.deploy_to}/shared/rake-db-created"

      command <<-EOH
      bundle exec rake db:create db:migrate && touch #{new_resource.deploy_to}/shared/rake-db-created
      EOH
    end

    Chef::Log.info "Running rake db:seed (if required)"
    rbenv_execute "rake-db-seed" do
      user new_resource.user
      cwd release_path
      environment environment_options

      ruby_version node['huginn']['ruby_version']
      creates "#{new_resource.deploy_to}/shared/rake-db-seeded"

      command <<-EOH
      bundle exec rake db:seed && touch #{new_resource.deploy_to}/shared/rake-db-seeded
      EOH
    end

    Chef::Log.info "Running rake db:migrate"
    rbenv_execute "rake-db-migrate" do
      user new_resource.user
      cwd release_path
      environment environment_options

      ruby_version node['huginn']['ruby_version']

      command "bundle exec rake db:migrate"
    end
  end

  before_symlink do
    Chef::Log.info "Create directory layout in shared"
    %w(config config/unicorn log tmp tmp/pids tmp/sockets).each do |dir|
      directory "#{new_resource.deploy_to}/shared/#{dir}" do
        owner new_resource.user
        group new_resource.group
        recursive true
      end
    end

    Chef::Log.info "Write Unicorn Production Config"
    template "Write Unicorn Production Config" do
      owner new_resource.user
      group new_resource.group

      source "unicorn/production.rb.erb"
      path "#{new_resource.deploy_to}/shared/config/unicorn/production.rb"

      variables({
        :huginn => node['huginn']
      })

      action :create
    end

    Chef::Log.info "Write Nginx Config"
    template "Write Nginx Config" do
      owner "root"
      group "root"

      source "nginx.conf.erb"
      path "/etc/nginx/conf.d/huginn.conf"

      variables({
        :huginn => node['huginn']
      })

      action :create
    end
  end

  symlinks(
    # Default
    "system" => "public/system",
    "pids" => "tmp/pids",
    "log" => "log",
    # Custom
    "config/unicorn" => "config/unicorn"
  )

  before_restart do
    Chef::Log.info "Export Huginn service"
    rbenv_execute "Export Huginn service" do
      ruby_version node['huginn']['ruby_version']
      cwd release_path

      command "bundle exec foreman export upstart /etc/init -a huginn -u #{new_resource.user} -l log"
    end

    Chef::Log.info "Enable/Restart Huginn service"
    service "huginn" do
      provider Chef::Provider::Service::Upstart
      action [:enable, :restart]
    end

    Chef::Log.info "Enable/Restart Nginx service"
    service "nginx" do
      action [:enable, :restart]
    end
  end

end
